src/pages/docs/canvas/tags/apply.md
src/pages/docs/canvas/tags/autoescape.md
src/pages/docs/canvas/tags/block.md
src/pages/docs/canvas/tags/deprecated.md
src/pages/docs/canvas/tags/do.md
src/pages/docs/canvas/tags/embed.md
src/pages/docs/canvas/tags/extends.md
src/pages/docs/canvas/tags/for.md
src/pages/docs/canvas/tags/from.md
src/pages/docs/canvas/tags/if.md
src/pages/docs/canvas/tags/import.md
src/pages/docs/canvas/tags/include.md
src/pages/docs/canvas/tags/macro.md
src/pages/docs/canvas/tags/set.md
src/pages/docs/canvas/tags/use.md
src/pages/docs/canvas/tags/verbatim.md
src/pages/docs/canvas/tags/with.md
src/pages/docs/getting-started/create.md
tailwind.config.js

This PR adds all the documentation for Canvas tags from the close sourced docs (slowly being deprecated in favour of this repo).

Add documentation for Canvas tags

---

package-lock.json
package.json
src/components/AppLink.tsx
src/components/Code.tsx
src/components/Contribution.tsx
src/components/Header.tsx
src/components/TableOfContents.tsx
src/pages/_app.tsx
src/pages/_document.tsx
src/pages/docs/canvas/getting-started/overview.md
src/pages/docs/canvas/tags/apply.md
src/pages/docs/canvas/tags/autoescape.md
src/pages/docs/canvas/tags/block.md
src/pages/docs/canvas/tags/deprecated.md
src/pages/docs/canvas/tags/do.md
src/pages/docs/canvas/tags/embed.md
src/pages/docs/canvas/tags/extends.md
src/pages/docs/canvas/tags/for.md
src/pages/docs/canvas/tags/from.md
src/pages/docs/canvas/tags/if.md
src/pages/docs/canvas/tags/include.md
src/pages/docs/canvas/tags/macro.md
src/pages/docs/canvas/tags/set.md
src/pages/docs/canvas/tags/use.md
src/pages/docs/canvas/tags/verbatim.md
src/pages/docs/canvas/tags/with.md
src/pages/docs/getting-started/create.md
src/styles/main.css
src/styles/prism.css
tailwind.config.js

This PR adds code highlighting to the Code component using PrismJS

feat: Improve code component

---

package-lock.json
package.json
src/components/AppLink.tsx
src/components/Code.tsx
src/components/Header.tsx
src/components/Search.tsx
src/components/Sidebar.tsx
src/components/TableOfContents.tsx
src/layouts/DocumentationLayout.tsx
src/markdoc/nodes/link.markdoc.ts
src/navigation/documentation.ts
src/styles/main.css
tailwind.config.js

This PR updates the application to NextJS v13, including several styling fixes to the navigation sidebar.

feat: upgrade to NextJS v13

---

src/components/Header.tsx
src/components/Sidebar.tsx
src/navigation/documentation.ts
src/pages/docs/canvas/getting-started/filters-functions.md
src/pages/docs/canvas/getting-started/templating.md
src/pages/docs/canvas/getting-started/variables.md

This PR adds the getting started documentation for the Canvas templating language. There are also improvements to the sidebar navigation to make it easier to navigate the large list.

add documentation for Canvas getting started guide

---

src/components/Callout.tsx
src/components/Contribution.tsx
src/components/Heading.tsx
src/components/Sidebar.tsx
src/components/TableOfContents.tsx
src/markdoc/tags/callout.markdoc.ts
src/markdoc/tags/index.ts
src/navigation/documentation.ts
src/pages/docs/courier/commands.md
src/pages/docs/courier/configuration.md
src/pages/docs/courier/installation.md
src/pages/docs/courier/upgrade.md
src/utils/collectHeadings.ts

This PR adds the documentation for Blutui Courier. The addition of these docs required a `Callout` component to be created, so as part of this PR there is a new `Callout` component available for use in the docs.

documentation: Blutui Courier

---

src/markdoc/nodes/heading.markdoc.ts
src/pages/docs/canvas/functions/agent.md
src/pages/docs/canvas/functions/asset.md
src/pages/docs/canvas/functions/attribute.md
src/pages/docs/canvas/functions/block.md
src/pages/docs/canvas/functions/cms-audio.md
src/pages/docs/canvas/functions/cms-button.md
src/pages/docs/canvas/functions/cms-code.md
src/pages/docs/canvas/functions/cms-embed.md
src/pages/docs/canvas/functions/cms-heading.md
src/pages/docs/canvas/functions/cms-image.md
src/pages/docs/canvas/functions/cms-list.md
src/pages/docs/canvas/functions/cms-quote.md
src/pages/docs/canvas/functions/cms-text.md
src/pages/docs/canvas/functions/cms-video.md
src/pages/docs/canvas/functions/cms.md
src/pages/docs/canvas/functions/constant.md
src/pages/docs/canvas/functions/cycle.md
src/pages/docs/canvas/functions/date.md
src/pages/docs/canvas/functions/deprecated.md
src/pages/docs/canvas/functions/dump.md
src/pages/docs/canvas/functions/include.md
src/pages/docs/canvas/functions/max.md
src/pages/docs/canvas/functions/min.md
src/pages/docs/canvas/functions/parent.md
src/pages/docs/canvas/functions/random.md
src/pages/docs/canvas/functions/range.md
src/pages/docs/canvas/functions/recaptcha.md
src/pages/docs/canvas/functions/source.md

This PR adds documentation for Canvas functions. This PR also updates the markdoc heading node to convert `/` to `-` when generating an ID.

documentation: Canvas functions

---

next.config.js
src/components/AppImage.tsx
src/markdoc/nodes/image.markdoc.ts
src/markdoc/nodes/index.ts
src/markdoc/tags/index.ts
src/pages/docs/getting-started/create.md
src/pages/docs/intellisense.md

This PR adds support for a custom `image` node using the NextJS Image component.

add custom AppImage component

---

src/components/Header.tsx

This PR adds the actual links that were missing in the Header component.

add missing header links

---

.vscode/launch.json
src/components/Sidebar.tsx
src/components/TableOfContents.tsx
src/styles/main.css

This PR makes the sidebar elements more visible. This PR also adds support for VSCode debugging.

make sidebar element more visible

---

src/layouts/DocumentationLayout.tsx
src/pages/index.tsx

This PR adds a small footer to the DocumentationLayout component.

add small footer to DocumentationLayout

---

src/components/Header.tsx
src/components/Sidebar.tsx
src/layouts/DocumentationLayout.tsx
src/layouts/FullPageLayout.tsx
src/pages/index.tsx
src/styles/main.css
tailwind.config.js

This PR adds a homepage to the app.

Add homepage content

---

package-lock.json
src/pages/index.tsx

This PR updates the homepage content to make it easier to navigate through the app.

Update homepage content

---

src/components/Sidebar.tsx
src/components/TableOfContents.tsx
src/pages/index.tsx
src/styles/docsearch.css
tailwind.config.js

This PR updates the application to use the Blutui colour scheme which has been adapted to use Tailwind's colour system.

add Blutui colour scheme

---

src/components/Sidebar.tsx
src/pages/_app.tsx
src/pages/changelog/index.md
src/pages/docs/courier/commands.md
src/pages/docs/courier/configuration.md
src/pages/docs/courier/getting-started.md
src/pages/docs/index.md

This PR updates the Courier documentation to remove `token` from the project `courier.json` file. This PR also adds the docs for using the new `courier login` command.

update docs to show usage of Courier v0.5.0

---

src/components/Badge.tsx
src/components/Heading.tsx
src/markdoc/tags/badge.markdoc.ts
src/markdoc/tags/index.ts
src/pages/changelog/index.md

This PR adds a new `badge` tag and `Badge` component to the application. This component has been added to replace the headings in the changelog. Adding badges makes the changelog more visually appealing.

Add badge component

---

src/layouts/DocumentationLayout.tsx
src/layouts/FullPageLayout.tsx

This PR adds `id`s so that we can configure Algolia's Crawler to target the correct elements.

Add ids to be used for Algolia's Crawler

---

src/pages/docs/courier/getting-started.md

This PR updates the getting started with Courier guide to include how to use `courier login` after creating a new token.

add information on how to use token with courier login command

---

src/pages/changelog/index.md

This PR updates the changelog to include changed between 1 Feb 23 - 20 Feb 23.

update changelog to include Feb 2023 changes

---

package-lock.json
package.json
tailwind.config.ts

This PR updates the Tailwind CSS config to typescript and updates `tailwindcss` to `v3.3`.

Update Tailwind CSS config to Typescript

---

src/pages/changelog/index.md

This PR adds the changelog for February 28, 2023.

add changelog for 2023-02-28

---

src/pages/changelog/index.md

This PR adds the changelog for 9 March 2023.

Add changelog for 9 March 2023

---

package-lock.json
package.json

This PR updates Next.js to `13.3`. This PR also includes updates to the dependencies.

Update to Next.js 13.3

---

src/components/Callout.tsx
src/components/Heading.tsx
src/components/Sidebar.tsx
src/components/TableOfContents.tsx
src/layouts/DocumentationLayout.tsx
src/pages/index.tsx

This PR adds responsiveness to the application.

Add responsiveness

---

package-lock.json
src/components/Card.tsx
src/components/Code.tsx
src/markdoc/tags/card.markdoc.ts
src/markdoc/tags/index.ts
src/pages/docs/courier/getting-started.md

This PR adds a card tag to markdown files and updates the Courier installation page to make use of the newly created card tag.

feat: add card tag for markdoc

---

src/components/Button.tsx
src/components/Callout.tsx
src/pages/index.tsx

This PR adds a `Button` component to the app.

feat: add button component

---

package-lock.json
package.json
src/components/Card.tsx
src/components/Header.tsx
src/utils/collectHeadings.ts

This PR updates all dependencies to the latest version.

chore: update dependencies

---

src/layouts/DocumentationLayout.tsx
src/layouts/FullPageLayout.tsx
src/pages/changelog/index.md

This PR updates the changelog to include the latest changes.

update changelog to latest version (v1.41.0)

---

src/pages/docs/getting-started/create.md

This PR adds filenames to the code fences in the getting started guide.

Update create project docs

---

src/pages/docs/canvas/getting-started/expressions.md
src/pages/docs/canvas/getting-started/filters-functions.md
src/pages/docs/canvas/getting-started/overview.md
src/pages/docs/canvas/getting-started/templating.md
src/pages/docs/canvas/getting-started/variables.md
src/pages/docs/getting-started/create.md

I have added a note to the bottom of the canvas getting started section to remind people to push and also add a new section into the getting started page after installing courier

addednote/ tip to people using docs to run courier push to see changes

---

src/pages/changelog/index.md

This PR updates the changelog to include the latest changes as of 17 July 2023.

update changelog: 17 July 2023

---

package-lock.json
src/markdoc/partials/create-courier-token.md
src/pages/docs/courier/installation/linux.md
src/pages/docs/courier/installation/macos.md
src/pages/docs/courier/installation/windows.md

This PR converts the "Create Courier token" content into a partial to avoid duplication. This PR also fixes grammatical errors in the newly create partial.

fix: convert duplicate content to partial

---

package-lock.json
package.json
src/pages/_app.tsx

This PR adds Vercel Analytics to the developer documentation.

feat: add analytics component

---

src/components/Header.tsx
src/pages/_app.tsx
src/pages/docs/canvas/filters/striptags.md
src/pages/docs/canvas/functions/parent.md
src/pages/docs/canvas/getting-started/expressions.md
src/pages/docs/canvas/getting-started/filters-functions.md
src/pages/docs/canvas/getting-started/overview.md
src/pages/docs/canvas/getting-started/templating.md
src/pages/docs/canvas/getting-started/variables.md
src/pages/docs/canvas/tags/block.md
src/pages/docs/canvas/tags/embed.md
src/pages/docs/canvas/tags/extends.md
src/pages/docs/canvas/tags/if.md
src/pages/docs/canvas/tags/macro.md
src/pages/docs/getting-started/create.md
tailwind.config.ts

This PR adds the docs for the spread operator and includes several improvements, including adding the Inter font.

feat: add spread operator docs + improvements

---

src/pages/changelog/index.md

This PR adds a changelog for the changes deployed on July 28, 2023.

chore: add changelog for 28 July 2023

---

LICENSE

This PR adds the MIT license for the repo.

feat: Add license

---

src/components/badge.tsx
src/components/button.tsx
src/components/header.tsx
src/components/sidebar.tsx
src/components/step.tsx
src/layouts/documentation.tsx
src/layouts/full-page.tsx
src/layouts/guides.tsx
src/pages/404.tsx
src/pages/_app.tsx
src/pages/_document.tsx
src/pages/guides/index.tsx
src/pages/index.tsx

This PR updates the default font from `Inter` to `Manrope`.

feat: update font from Inter to Manrope

---

.vscode/settings.json
src/pages/changelog/index.md
src/pages/guides/index.tsx

This PR includes the changelog for the changes made to the platform in September 2023. This PR also includes a change to detect Tailwind CSS classes within the `cn` function.

chore: update the changelog to include changes for September

---

package-lock.json
package.json
src/pages/guides/index.tsx

This PR fixes the prettier formatting and attempts to make guides more searchable.

fix: search indexing & prettier

---

src/navigation/guides.ts
src/pages/guides/send-form-submissions-to-zapier.md

This PR adds the guide to use webhooks with Zapier.

add form.submission.created to Zapier guide

---

src/navigation/guides.ts
src/pages/guides/add-recaptcha-2-to-a-form.md

This PR adds the reCAPTCHA v2 integration guide.

feat: add recaptcha v2 integration guide

---

package-lock.json
src/components/sidebar.tsx
src/components/step.tsx
src/layouts/guides.tsx
src/navigation/guides.ts
src/pages/guides/add-recaptcha-2-to-a-form.md
src/pages/guides/add-recaptcha-3-to-a-form.md
src/pages/guides/index.tsx

This PR adds the reCAPTCHA v3 integration guide.

Guide recaptcha 3 forms

---

src/pages/index.tsx

update Twitter to X

---

src/navigation/guides.ts
src/pages/docs/canvas/getting-started/expressions.md
src/pages/docs/canvas/getting-started/filters-functions.md
src/pages/docs/canvas/getting-started/templating.md
src/pages/docs/canvas/tags/autoescape.md
src/pages/guides/create-project.md

This PR adds the "How do I create a Blutui project?". This PR also fixes 404 errors that were detected by Algolia.

feat: add create project guide

---

src/components/callout.tsx
src/components/card.tsx
src/components/step.tsx
src/navigation/guides.ts
src/pages/guides/what-is-blutui-canvas.md
src/styles/main.css

This PR adds the "What is a Blutui Canvas" guide. It also updates the `card` and `callout` components to be used inside a `step` component.

add What is a Blutui Canvas guide

---

src/navigation/guides.ts
src/pages/guides/create-form.md

This PR adds the guide on how to create a form in Blutui.

feat: Add Create a form guide

---

src/navigation/guides.ts
src/pages/guides/make-the-most-out-of-canvas.md

This PR adds the "How can I make the most out of Blutui Canvas?" guide.

feat: add make the most out of Canvas guide

---

src/layouts/documentation.tsx
src/layouts/guides.tsx
src/navigation/guides.ts
src/pages/guides/index.tsx
src/pages/guides/send-form-submissions-to-an-email-address.md

This PR adds the guide on how to send form submissions to an email address

add guide on how to send form submissions to email

---

package-lock.json

This PR updates Next.js to the latest stable release

chore: update Next.js

---

src/navigation/guides.ts
src/pages/guides/use-a-package-manager-in-a-project.md

This PR adds the "How do I use a package manager in a Blutui project?" guide

feat: add how to use a package manager guide

---

src/navigation/guides.ts
src/pages/guides/use-parcel-js-in-a-project.md

This PR adds a guide on how to use Parcel.js with a Blutui project.

feat: add Parcel.js guide

---

package.json
src/navigation/guides.ts
src/pages/guides/use-a-package-manager-in-a-project.md
src/pages/guides/use-tailwind-css-in-a-project.md

This PR adds the guide for using Tailwind CSS in a Blutui Project

feat: Add guide for using Tailwind CSS

---

src/pages/_app.tsx

This PR adds the meta tags required for opengraph titles and descriptions.

feat: Add opengraph tags for title and description

---

src/pages/docs/canvas/functions/deprecated.md

This PR removes all collection, forms and menus related functions from the deprecated functions page.

remove: Collections, forms, and menus functions from deprecated page

---

src/pages/changelog/index.md

This PR adds the changelog for October 2023

chore: Add changelog for October 2023

---

src/navigation/documentation.ts
src/pages/docs/canvas/tags/form.md

This PR adds the documentation for the new `{% form %}` tag.

feat: Add documentation for `form` tag

---

src/pages/docs/canvas/tags/form.md

This PR adds information about the available variables inside the `form` tag.

feat: Add info about form tag variables

---

package-lock.json
package.json
src/components/badge.tsx
src/components/button.tsx
src/components/card.tsx
src/components/footer.tsx
src/components/header.tsx
src/components/table-of-contents.tsx
src/pages/guides/index.tsx
src/utils/slugify.ts
tailwind.config.ts

This PR adds a filtering system for guide tags. It allows you to filter the list of guides using checkbox filters.

feat: Add tag filter for guides

---

src/pages/docs/index.md

This PR adds additional content to the `/docs` page.

change: Add more content to the introduction page

---

src/pages/changelog/index.md

This PR adds the changelog for 21 December 2023

chore: Add changelog for 21 December 2023

---

src/components/callout.tsx

This PR changes emojis in the callout component to icons.

change: Use icons instead of emoji

---

src/components/button.tsx
src/components/card.tsx
src/components/changelog.tsx
src/components/header.tsx
src/components/step.tsx
src/pages/index.tsx

This PR fixes some responsive styles for several components to ensure they display correctly for mobile and tablet.

fix: Responsive styles for components

---

src/components/ask-ai-button.tsx
src/components/header.tsx
src/types/index.d.ts
src/types/index.ts
tsconfig.json

This PR adds the Glime chatbot to the project, allowing users to ask questions in a ChatGPT like way.

feat: Add Glime AI chatbot

---

src/components/card.tsx

Updating export function of card comp

updated export format

---

src/components/ask-ai-button.tsx

This PR updates the AI Button Component to only show the button once the Glime script has loaded.

fix: show button when script loaded

---

.github/dependabot.yml

change: Update dependabot interval to daily

---

src/components/sidebar.tsx
src/components/step.tsx
src/components/table-of-contents.tsx
src/pages/_document.tsx
src/styles/main.css

This PR removes the flash that occurs when loading the project in the browser.

fix: theme change flash

---

src/pages/guides/create-form.md

fix form guide code

---

src/components/header.tsx
src/components/icons/queue-list.tsx
src/pages/docs/getting-started/create.md

fix: update form example

---

src/pages/docs/getting-started/create.md
src/pages/guides/create-project.md

fix: update console URL

---

src/components/header.tsx

This PR fixes the active header item styles since it was overflowing the header itself.

fix: header active item styles

---

src/components/icons/queue-list.tsx
src/pages/index.tsx

This PR updates the changelog icon on the homepage to match the icon in the header.

change changelog icon to match header

---

.github/dependabot.yml
package-lock.json
package.json
src/pages/changelog/index.md

This PR updates the changelog to includes the changes made between 12 March 2024 an 12 April 2024. This PR also updates NextJS to the latest version.

chore: Add changelog until 12 April 2024

---

src/navigation/guides.ts
src/pages/guides/use-blutui-ai-in-a-project.md
src/pages/guides/use-tailwind-css-in-a-project.md

add ai components guide

---

src/components/prompt.tsx
src/markdoc/tags/index.ts
src/markdoc/tags/prompt.markdoc.ts
src/navigation/documentation.ts
src/pages/docs/ai-components/getting-started.md

AI components getting started

---

src/pages/docs/ai-components/getting-started.md
src/pages/guides/use-blutui-ai-in-a-project.md

update ai guide

---

.gitignore
package.json
src/pages/docs/courier/commands.md

Updated the courier commands page

updated courier command text

---

package.json
src/pages/changelog/index.md

This PR adds the changelog for May & June 2024

chore: Update changelog for May & June

---

src/components/header.tsx

This PR disables the Ask AI button while we investigate and alternative to Glime AI.

chore: Disable ask AI button

---

src/markdoc/partials/api/console/role-response-list.md
src/markdoc/partials/api/console/role-response-parameters.md
src/markdoc/partials/api/console/role-response.md
src/navigation/api/console.ts
src/pages/api-reference/console/projects/create.md
src/pages/api-reference/console/projects/update.md
src/pages/api-reference/console/roles/create.md
src/pages/api-reference/console/roles/list.md
src/pages/api-reference/console/roles/remove.md
src/pages/api-reference/console/roles/retrieve.md
src/pages/api-reference/console/roles/update.md

feat: Add Roles resource to Console API

---

package-lock.json
src/components/header.tsx
src/pages/index.tsx

This PR makes the header component slightly for elegant by simplifying the borders.

feat: Simplify header

---

src/pages/schemas/v1/schema.json.tsx

feat: Add courier.json schema files

---

src/components/changelog.tsx
src/pages/api-reference/console/projects/create.md
src/pages/changelog/index.md
src/utils/use-theme.ts

This PR updates the changelog till 17 October 2024

chore: Add changelog until 17 Oct 24

---

package-lock.json
package.json
src/components/heading.tsx

This PR upgrades the app to Next.js 15

chore: Upgrade to Next.js 15

---

src/navigation/api/console.ts

This PR deprecates the republish API.

deprecate: Republish API

---

src/markdoc/partials/create-courier-token.md
src/pages/docs/courier/commands.md
src/pages/docs/courier/configuration.md
src/pages/docs/courier/getting-started.md
src/pages/docs/courier/installation/linux.md
src/pages/docs/courier/installation/macos.md
src/pages/docs/courier/installation/windows.md
src/pages/docs/courier/upgrade.md
src/pages/docs/getting-started/create.md
src/pages/guides/install-courier-on-macos.md
src/pages/guides/preview-project-with-courier.md

This PR updates the Courier docs.

chore: Update Courier docs

---

src/pages/guides/use-blutui-ai-in-a-project.md

This PR updates the AI components guide

change: updated ai-guide

---

package-lock.json
package.json
src/markdoc/partials/api/console/cassette-response-list.md
src/markdoc/partials/api/console/cassette-response-parameters.md
src/markdoc/partials/api/console/cassette-response.md
src/navigation/api/console.ts
src/pages/api-reference/console/cassettes/create.md
src/pages/api-reference/console/cassettes/duplicate.md
src/pages/api-reference/console/cassettes/remove.md
src/pages/api-reference/console/cassettes/retrieve.md
src/pages/api-reference/console/cassettes/update.md
src/pages/api-reference/console/projects/cassettes.md

This PR adds the Cassette API docs to the Console API.

feat: Add Cassette resource API

---

src/markdoc/partials/api/console/invite-response-list.md
src/markdoc/partials/api/console/invite-response-parameters.md
src/markdoc/partials/api/console/invite-response.md
src/navigation/api/console.ts
src/pages/api-reference/console/invites/list.md
src/pages/api-reference/console/invites/remove.md
src/pages/api-reference/console/invites/update.md

This PR adds the API reference for the invites resource in the Console API.

feat: Add API reference for invites resource

---

src/markdoc/partials/api/admin/redirect-response-list.md
src/markdoc/partials/api/admin/redirect-response-parameters.md
src/markdoc/partials/api/admin/redirect-response.md
src/navigation/api/admin.ts
src/pages/api-reference/admin/redirects/create.md
src/pages/api-reference/admin/redirects/list.md
src/pages/api-reference/admin/redirects/remove.md
src/pages/api-reference/admin/redirects/retrieve.md
src/pages/api-reference/admin/redirects/update.md

feat: Add admin redirect
